### ISSUE TITLE
Unable to pip install erdos==0.3.1

### ISSUE THREAD

**Issue by armaangoel78** [erdos-project/erdos#169]
I'm unable to install using `pip3 install erdos==0.3.1`. I've tried 3.9 and 3.8, and my friend tried 3.7, but none of these work. My full error message is below. Thanks!

```
ERROR: Could not find a version that satisfies the requirement erdos==0.3.1 (from versions: 0.1, 0.1.1, 0.1.2, 0.1.3, 0.2.0)
ERROR: No matching distribution found for erdos==0.3.1
```

**Comment by ICGog** [comment]
We do have a pip for Python 3.8. You can see here for what Python versions we have wheels: https://pypi.org/project/erdos/0.3.1/#files . 

Are you using Windows or MacOS, which are not supported by us? Or are you running an older version of pip?

Alternatively, you can install ERDOS manually by following the instructions from [here](https://github.com/erdos-project/erdos#python-installation).

**Comment by armaangoel78** [comment]
Using mac, that's probably the problem. Thanks!
