### ISSUE TITLE
[ROS] Automatically set publisher buffer size based on message types

### ISSUE THREAD

**Issue by ICGog** [erdos-project/erdos#5]
The ROS publisher and subscriber API expects users to specify queue sizes and buffers sizes. Users are expected to provide a buffer size that is greater than the size of all messages in the queue. Otherwise, ROS drops messages.

Update `ros_output_data_stream.py` to automatically compute the size of the buffer based on the size of the queues.

**Comment by charliedua** [comment]
I was looking at `ros_output_data_stream.py` and I couldn't find the buffer size you mentioned. However, I saw a buffer_size in `buffer_actor.py`, were you talking about the initialization of `buffer_actor`.
So the issue wasn't clear enough for me. Could you elaborate?

**Comment by ICGog** [comment]
@charliedua Thanks for looking into it. You couldn't find buffer size in `ros_output_data_stream.py` because we don't currently set it. `rospy.Publisher` has two arguments that control queue and buffer sizes: `queue_size` and `buff_size`. `buff_size` must be greater than `queue_size * size of message`, but our code doesn't enforce that because we use the default buff_size. You can read this [page](http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers) if you want to find more about ROS queues.

**Comment by ICGog** [comment]
Closing this issue because we've migrated away from ROS.
