### ISSUE TITLE
[Installation] tests fail

### ISSUE THREAD

**Issue by theophilee** [erdos-project/erdos#52]
Hi,

First of all amazing work, the pylot repo seems very useful and well structured. 
I'm trying to install the erdos library to be able to work with pylot without docker containers, but I run into issues.

After I run "source ./install.sh", I run the tests but both fail. Below is the stack trace for ros:

~/Software/erdos$ python tests/sum_squares_test.py --framework=ros
I0713 12:59:04.849879 140101035767616 topics.py:1132] topicmanager initialized
/home/theophile/Software/erdos/erdos/ros/ros_output_data_stream.py:40: SyntaxWarning: The publisher should be created with an explicit keyword argument 'queue_size'. Please see http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers for more information.
  self.uid, String, latch=True, queue_size=None)
/home/theophile/Software/erdos/erdos/ros/ros_output_data_stream.py:40: SyntaxWarning: The publisher should be created with an explicit keyword argument 'queue_size'. Please see http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers for more information.
  self.uid, String, latch=True, queue_size=None)
/home/theophile/Software/erdos/erdos/ros/ros_output_data_stream.py:40: SyntaxWarning: The publisher should be created with an explicit keyword argument 'queue_size'. Please see http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers for more information.
  self.uid, String, latch=True, queue_size=None)
/home/theophile/Software/erdos/erdos/ros/ros_output_data_stream.py:40: SyntaxWarning: The publisher should be created with an explicit keyword argument 'queue_size'. Please see http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers for more information.
  self.uid, String, latch=True, queue_size=None)
/home/theophile/Software/erdos/erdos/ros/ros_output_data_stream.py:40: SyntaxWarning: The publisher should be created with an explicit keyword argument 'queue_size'. Please see http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers for more information.
  self.uid, String, latch=True, queue_size=None)
Process Process-3:
Traceback (most recent call last):
  File "/home/theophile/anaconda3/envs/pylot/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/theophile/anaconda3/envs/pylot/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/theophile/Software/erdos/erdos/ros/ros_executor.py", line 32, in _execute_helper
    op.execute()
  File "tests/sum_squares_test.py", line 37, in execute
    self.publish_random_number()
  File "/home/theophile/Software/erdos/erdos/utils.py", line 50, in wrapper
    func(*args, **kwargs)
  File "tests/sum_squares_test.py", line 33, in publish_random_number
    self.get_output_stream("integer_out").send(output_msg)
  File "/home/theophile/Software/erdos/erdos/ros/ros_output_data_stream.py", line 27, in send
    self.publisher.publish(msg)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py", line 882, in publish
    self.impl.publish(data)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py", line 1066, in publish
    serialize_message(b, self.seq, message)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/msg.py", line 152, in serialize_message
    msg.serialize(b)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/std_msgs/msg/_String.py", line 55, in serialize
    _x = _x.encode('utf-8')
AttributeError: 'bytes' object has no attribute 'encode'

I'm using python 3.6 (supported by Carla), and ros seems to be correctly installed:
~/Software/erdos$ rosversion -d
melodic

With ray, the stack trace is:

~/Software/erdos$ python tests/sum_squares_test.py --framework=ray
2019-07-13 13:07:58,251	INFO node.py:498 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-07-13_13-07-58_251164_128678/logs.
2019-07-13 13:07:58,354	INFO services.py:409 -- Waiting for redis server at 127.0.0.1:23687 to respond...
2019-07-13 13:07:58,463	INFO services.py:409 -- Waiting for redis server at 127.0.0.1:13918 to respond...
2019-07-13 13:07:58,464	INFO services.py:806 -- Starting Redis shard with 10.0 GB max memory.
2019-07-13 13:07:58,472	INFO node.py:512 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-07-13_13-07-58_251164_128678/logs.
2019-07-13 13:07:58,473	WARNING services.py:1298 -- Warning: Capping object memory store to 20.0GB. To increase this further, specify `object_store_memory` when calling ray.init() or ray start.
2019-07-13 13:07:58,473	INFO services.py:1446 -- Starting the Plasma object store with 20.0 GB memory using /dev/shm.
I0713 13:07:59.807582 140074814605120 ray_executor.py:53] Executing input_op
I0713 13:07:59.818301 140074814605120 ray_executor.py:53] Executing output_op
Traceback (most recent call last):
  File "tests/sum_squares_test.py", line 118, in <module>
    app.run(main)
  File "/home/theophile/anaconda3/envs/pylot/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/theophile/anaconda3/envs/pylot/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "tests/sum_squares_test.py", line 115, in main
    graph.execute(FLAGS.framework)
  File "/home/theophile/Software/erdos/erdos/graph.py", line 200, in execute
    executor.execute()
  File "/home/theophile/Software/erdos/erdos/ray/ray_executor.py", line 48, in execute
    self.op_handle.dependent_op_handles))
  File "/home/theophile/anaconda3/envs/pylot/lib/python3.6/site-packages/ray/worker.py", line 2195, in get
    raise value
ray.exceptions.RayTaskError: ray_RayOperator:setup_streams() (pid=128750, host=theophile-desktop)
  File "/home/theophile/Software/erdos/erdos/ray/ray_operator.py", line 162, in setup_streams
    self._op._internal_setup_streams()
  File "/home/theophile/Software/erdos/erdos/op.py", line 182, in _internal_setup_streams
    output_stream.setup()
  File "/home/theophile/Software/erdos/erdos/ray/ray_output_data_stream.py", line 44, in setup
    for actor_handle in self._dependant_op_handles
  File "/home/theophile/Software/erdos/erdos/ray/ray_output_data_stream.py", line 44, in <listcomp>
    for actor_handle in self._dependant_op_handles
AttributeError: 'str' object has no attribute 'on_msg'

Thank you very much for your help!
Theo

**Comment by ICGog** [comment]
@theophilee ROS does not support Python 3 :(. Can you please try running it using Python 2?

Recently, we've focused all our effort on Pylot, which we execute using ROS, and thus our Ray support is out of date. However, please stay tuned because we're in the process of revamping ERDOS :).

IMHO, the easiest way to install Pylot natively is to run the same commands as we do in the Dockerfile: https://github.com/erdos-project/pylot/blob/master/docker/Dockerfile_pylot_Ubuntu18.04 .

**Comment by theophilee** [comment]
Thank you for your quick reply, the erdos ros test works with Python 2 :)

When I follow the Dockerfile commands to install pylot natively, I get an "ImportError: No module named open3d" when running "python pylot.py --flagfile=configs=configs/ground_agent_e2e.conf".

Running "pip install -e ./" in "erdos/workspace/pylot/" installs open-3d version 0.3.0.0 in my conda environment, but I still get an "ImportError: No module named open3d". If I install open3d with "pip install open3d-python", I can import open3d but run into different errors later on.

Below is my conda environment:
# packages in environment at /home/theophile/anaconda3/envs/pylot:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_tflow_select             2.1.0                       gpu  
absl-py                   0.7.1                    py27_0  
astor                     0.7.1                    py27_0  
atomicwrites              1.3.0                    pypi_0    pypi
attrs                     19.1.0                   py27_1  
backports                 1.0                        py_2  
backports.shutil_get_terminal_size 1.0.0                    py27_2  
backports.weakref         1.0.post1                  py_1  
backports_abc             0.5                        py_0  
blas                      1.0                         mkl  
bleach                    3.1.0                    py27_0  
c-ares                    1.15.0               h7b6447c_1  
ca-certificates           2019.5.15                     0  
catkin-pkg                0.4.12                   pypi_0    pypi
certifi                   2019.6.16                py27_0  
cffi                      1.12.3                   pypi_0    pypi
chardet                   3.0.4                    pypi_0    pypi
click                     7.0                      pypi_0    pypi
colorama                  0.4.1                    pypi_0    pypi
configparser              3.7.4                    py27_0  
contextlib2               0.5.5                    pypi_0    pypi
cudatoolkit               10.0.130                      0  
cudnn                     7.6.0                cuda10.0_0  
cupti                     10.0.130                      0  
decorator                 4.4.0                    py27_1  
defusedxml                0.6.0                      py_0  
docutils                  0.14                     pypi_0    pypi
entrypoints               0.3                      py27_0  
enum34                    1.1.6                    py27_1  
erdos                     0.1.2                     dev_0    <develop>
erdos-pylot               0.1                       dev_0    <develop>
faulthandler              3.1                      pypi_0    pypi
filelock                  3.0.12                   pypi_0    pypi
flatbuffers               1.11                     pypi_0    pypi
funcsigs                  1.0.2                    py27_0  
functools32               3.2.3.2                  py27_1  
futures                   3.2.0                    py27_0  
gast                      0.2.2                    py27_0  
gdown                     3.8.1                    pypi_0    pypi
gmp                       6.1.2                h6c8ec71_1  
google-pasta              0.1.7                    pypi_0    pypi
grpcio                    1.16.1           py27hf8bcb03_1  
h5py                      2.9.0            py27h7918eee_0  
hdf5                      1.10.4               hb1b8bf9_0  
idna                      2.8                      pypi_0    pypi
importlib-metadata        0.18                     pypi_0    pypi
intel-openmp              2019.4                      243  
ipaddress                 1.0.22                   py27_0  
ipykernel                 4.10.0                   py27_0  
ipython                   5.8.0                    py27_0  
ipython_genutils          0.2.0                    py27_0  
ipywidgets                7.4.2                    py27_0  
jinja2                    2.10.1                   py27_0  
jsonschema                3.0.1                    py27_0  
jupyter_client            5.2.4                    py27_0  
jupyter_core              4.5.0                      py_0  
keras-applications        1.0.8                      py_0  
keras-preprocessing       1.1.0                      py_1  
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libprotobuf               3.8.0                hd408876_0  
libsodium                 1.0.16               h1bed415_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
linecache2                1.0.0                    py27_0  
markdown                  3.1.1                    py27_0  
markupsafe                1.1.1            py27h7b6447c_0  
mistune                   0.8.4            py27h7b6447c_0  
mkl                       2019.4                      243  
mkl_fft                   1.0.12           py27ha843d7b_0  
mkl_random                1.0.2            py27hd81dba3_0  
mock                      3.0.5                    py27_0  
more-itertools            5.0.0                    pypi_0    pypi
nbconvert                 5.5.0                      py_0  
nbformat                  4.4.0                    py27_0  
ncurses                   6.1                  he6710b0_1  
notebook                  5.7.8                    py27_0  
numpy                     1.16.4           py27h7e9f1db_0  
numpy-base                1.16.4           py27hde5b4d6_0  
open-3d                   0.3.0.0                  pypi_0    pypi
open3d-original           0.3.0.0                  pypi_0    pypi
opencv-contrib-python     4.1.0.25                 pypi_0    pypi
openssl                   1.1.1c               h7b6447c_1  
packaging                 19.0                     pypi_0    pypi
pandoc                    2.2.3.2                       0  
pandocfilters             1.4.2                    py27_1  
pathlib2                  2.3.4                    py27_0  
pexpect                   4.7.0                    py27_0  
pickleshare               0.7.5                    py27_0  
pillow                    6.1.0                    pypi_0    pypi
pip                       19.1.1                   py27_0  
pluggy                    0.12.0                   pypi_0    pypi
pptk                      0.1.0                    pypi_0    pypi
prometheus_client         0.7.1                      py_0  
prompt_toolkit            1.0.15                   py27_0  
protobuf                  3.8.0            py27he6710b0_0  
ptyprocess                0.6.0                    py27_0  
py                        1.8.0                    pypi_0    pypi
pycparser                 2.19                     pypi_0    pypi
pygments                  2.4.2                      py_0  
pyrsistent                0.14.11          py27h7b6447c_0  
pytest                    4.6.4                    pypi_0    pypi
python                    2.7.16               h9bab390_0  
python-dateutil           2.8.0                    py27_0  
pyyaml                    5.1.1                    pypi_0    pypi
pyzmq                     18.0.0           py27he6710b0_0  
ray                       0.7.2                    pypi_0    pypi
readline                  7.0                  h7b6447c_5  
redis                     3.2.1                    pypi_0    pypi
requests                  2.22.0                   pypi_0    pypi
rospkg                    1.1.9                    pypi_0    pypi
scandir                   1.10.0           py27h7b6447c_0  
scipy                     1.2.1            py27h7c811a0_0  
send2trash                1.5.0                    py27_0  
setproctitle              1.1.10                   pypi_0    pypi
setuptools                41.0.1                   py27_0  
simplegeneric             0.8.1                    py27_2  
singledispatch            3.4.0.3                  py27_0  
six                       1.12.0                   py27_0  
sqlite                    3.28.0               h7b6447c_0  
tensorboard               1.14.0                   pypi_0    pypi
tensorflow                1.13.1          gpu_py27hcb41dfa_0  
tensorflow-base           1.13.1          gpu_py27h8d69cac_0  
tensorflow-estimator      1.14.0                   pypi_0    pypi
tensorflow-gpu            1.14.0                   pypi_0    pypi
termcolor                 1.1.0                    py27_1  
terminado                 0.8.2                    py27_0  
testpath                  0.4.2                    py27_0  
tk                        8.6.8                hbc83047_0  
torch                     0.4.1                    pypi_0    pypi
torchvision               0.2.1                    pypi_0    pypi
tornado                   5.1.1            py27h7b6447c_0  
tqdm                      4.32.2                   pypi_0    pypi
traceback2                1.4.0                    py27_0  
traitlets                 4.3.2                    py27_0  
unittest2                 1.1.0                    py27_0  
urllib3                   1.25.3                   pypi_0    pypi
wcwidth                   0.1.7                    pypi_0    pypi
webencodings              0.5.1                    py27_1  
werkzeug                  0.15.4                     py_0  
wheel                     0.33.4                   py27_0  
widgetsnbextension        3.4.2                    py27_0  
wrapt                     1.11.2                   pypi_0    pypi
xz                        5.2.4                h14c3975_4  
zeromq                    4.3.1                he6710b0_3  
zipp                      0.5.2                    pypi_0    pypi
zlib                      1.2.11               h7b6447c_3  

I really appreciate any insight you might have into why that happens, thank you again!
